SurveyOnline/SurveyOnline/Models/Survey.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.ComponentModel.DataAnnotations;

namespace SurveyOnline.Models
{
    public class Survey
    {
        public int ID { get; set; }
        [Required]
        [StringLength(255)]
        public string Title { get; set; }
        [Required]
        
        public string SurveyQuestion { get; set; }
        
        public Topic Topic { get; set; }
        [Required]
        public byte TopicId { get; set; }

        [StringLength(255)]
        public string Autohor { get; set; }
        public DateTime? Deadline { get; set; }
    }
}

SurveyOnline/SurveyOnline/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SurveyOnline.Models;
using SurveyOnline.ViewModels;
using System.Data.Entity;

namespace SurveyOnline.Controllers
{
    public class SurveyController : Controller
    { 
        private ApplicationDbContext _context;

        //Class contructor
        public SurveyController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Survey
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult New()
        {
            //var membershipTypes = _context.MembershipTypes.ToList();

            var viewModel = new SurveyFromModelView()
            {
                Survey = new Survey(),
                Topics = _context.Topics.ToList()
            };
            return View("SurveyForm", viewModel);
        }

        //Adding a new survey -  http post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Survey survey)
        {
            //Server side validation - start
            if (!ModelState.IsValid)
            {
                var viewModel = new SurveyFromModelView()
                {
                    Survey = survey,
                    Topics = _context.Topics.ToList()
                };

                return View("SurveyForm", viewModel);
            }
            //**********Server side validation - end *********
            if (survey.ID == 0)
            {
                _context.Surveys.Add(survey);
            }
            else
            {
                var surveyInDB = _context.Surveys.Single(s => s.ID == survey.ID);
                /*
                 * TryUpdateModel(surveyInDB);
                 * this is defualt method to update used by MS
                 * It has major security flow.
                 * 
                 * */
                //This manual way to it.
                surveyInDB.Title = survey.Title;
                surveyInDB.SurveyQuestion = survey.SurveyQuestion;
                surveyInDB.TopicId = survey.TopicId;
                surveyInDB.Autohor = survey.Autohor;
                surveyInDB.Deadline = survey.Deadline;

            }

            _context.SaveChanges();

            return RedirectToAction("Index", "Surveys");
        }

        public ActionResult List()
        {
            var surveys = _context.Surveys.Include(s=>s.Topic).ToList();
            return View(surveys);
        }
    }
}

SurveyOnline/SurveyOnline/Views/Survey/List.cshtml
@model IEnumerable<SurveyOnline.Models.Survey>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of surveys</h2>


@if (!Model.Any())
{
    <p>There are no Surveys availble.</p>
}
else
{
    <table class="table table-dark table-hover">
        <thread>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th colspan="3">Action</th>
                
            </tr>
        </thread>
        <tbody>
            @foreach (var s in Model)
            {
                <tr>
                    <td>@s.ID</td>
                    <td>@s.Title</td>
                    <td>@Html.ActionLink("Details", "Details", "Surveys", new { id = s.ID }, null)</td>
                    <td>@Html.ActionLink("Edit", "Edit", "Surveys", new { id = s.ID }, null)</td>
                    <td>@Html.ActionLink("Delete", "Delete", "Surveys", new { id = s.ID }, null)</td>


                </tr>
            }
        </tbody>
    </table>
}

SurveyOnline/SurveyOnline/Views/Survey/SurveyForm.cshtml
@model SurveyOnline.ViewModels.SurveyFromModelView
@{
    ViewBag.Title = "SurveyForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SurveyForm</h2>

@using (Html.BeginForm("Save", "Survey"))
{

    <a href="~/Survey/List">List of available surveys</a>
    @Html.ValidationSummary();
    <div class="form-group">
        @Html.LabelFor(s => s.Survey.Title)
        @Html.TextBoxFor(s => s.Survey.Title, new { @class = "form-control" })
        @Html.ValidationMessageFor(s => s.Survey.Title)

    </div>

    <div class="form-group">
        @Html.LabelFor(s => s.Survey.SurveyQuestion)
        @Html.TextBoxFor(s => s.Survey.SurveyQuestion, new { @class = "form-control" })
        @Html.ValidationMessageFor(s => s.Survey.SurveyQuestion)
    </div>
    <div class="form-group">
        @Html.LabelFor(s => s.Survey.Autohor)
        @Html.TextBoxFor(s => s.Survey.Autohor, new { @class = "form-control" })
        @Html.ValidationMessageFor(s => s.Survey.Autohor)
    </div>

    <div class="form-group">
        @Html.LabelFor(s => s.Survey.Deadline)
        @Html.TextBoxFor(s => s.Survey.Deadline, "{0:d MMM yyyy}", new { @class = "form-control" })
        @Html.ValidationMessageFor(s => s.Survey.Deadline)
    </div>

    <div class="form-group">
        @Html.LabelFor(s => s.Survey.Topic)
        @Html.DropDownListFor(s => s.Survey.Topic,
        new SelectList(Model.Topics, "ID", "Name"),
        "Select Topic Type", new { @class = "form-control" })
        @Html.ValidationMessageFor(s => s.Survey.Topic)
    </div>

   
    @Html.HiddenFor(s => s.Survey.ID)
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Save</button><br>

    <a href="~/Survey/New"> << Back </a>

}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}