VidPlace/VidPlace/Models/Rental.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace VidPlace.Models
{
    public class Rental
    {
        public int Id { get; set; }
        public DateTime DateRented { get; set; }
        public DateTime? DateReturned { get; set; }

        //Customer has a 1-* relation with rental
        //One rental belongs to one customer
        //One customer will have several rentals
        public Customer Customer { get; set; }
        [Required]
        public int CustomerId { get; set; }

        //Media has a *-* relation with rentals
        //A rental can have several medias and media can be part of several rentals
        public virtual List<Media> Medias { get; set; }

    }
}

VidPlace/VidPlace/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VidPlace.ViewModels;
using VidPlace.Models;

namespace VidPlace.Controllers
{
    public class RentalsController : Controller
    {
        //Class variables
        private ApplicationDbContext _context;

        //Class contructor
        public RentalsController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Rentals
        public ActionResult Index()
        {
            return View();
        }

        //GET : Rentals/Create
        public ActionResult Create(int id, string SearchString)
        {
            var viewModel = new RentalFormViewModel();

            viewModel.Customer = _context.Customers.Find(id);
            if (viewModel.Customer == null)
                return HttpNotFound();

            if(!String.IsNullOrWhiteSpace(SearchString))
            {
                viewModel.Medias = _context.Medias.Where(m => m.name.Contains(SearchString)).ToList();
            }
            
            return View(viewModel);
        }

        //POST : Rentals/Create
        [HttpPost]
        public ActionResult Create()
        {
            return View("RentalConfirmation");
        }


        }
}

VidPlace/VidPlace/Views/Rentals/Create.cshtml
@model VidPlace.ViewModels.RentalFormViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New Rental Record</h2>

<h3>@Model.Customer.Name</h3>

@using (Html.BeginForm("Create", "Rentals", FormMethod.Get))
{
    <p>
        Search for a Media to Rent: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

@if (Model.Medias != null)
{
    using (Html.BeginForm("Create", "Rentals"))
    {
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Media</th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Medias.Count - 1; i++)
                {
                    <tr>
                        <td>
                            <input type="checkbox"
                                   name="selectedMedias"
                                   value="@Model.Medias[i].ID" />
                            @Model.Medias[i].name
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        @Html.HiddenFor(m => m.Customer.ID)
        <button type="submit" class="btn btn-primary">Add Rental</button>
    }
}

VidPlace/VidPlace/Views/Rentals/RentalConfirmation.cshtml
@{
    ViewBag.Title = "RentalConfirmation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>RentalConfirmation</h2>